//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeeksForLess_test.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GeeksForLessTestDBEntities : DbContext
    {
        public GeeksForLessTestDBEntities()
            : base("name=GeeksForLessTestDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<Likes> Likes { get; set; }
        public virtual DbSet<Likes_targets> Likes_targets { get; set; }
        public virtual DbSet<Options> Options { get; set; }
        public virtual DbSet<Themes> Themes { get; set; }
        public virtual DbSet<Themes_messages> Themes_messages { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
    }
}
