//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeeksForLess_test.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Likes
    {
        public long Id { get; set; }
        public long Target { get; set; }
        public int Target_type { get; set; }
        public string Like_author { get; set; }
    
        public virtual Likes_targets Likes_targets { get; set; }
        public virtual AspNetUsers AspNetUsers { get; set; }
    }
}
