//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeeksForLess_test.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Themes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Themes()
        {
            this.Themes_messages = new HashSet<Themes_messages>();
            this.Themes1 = new HashSet<Themes>();
        }
    
        public long Id { get; set; }
        public string Name { get; set; }
        public string Author { get; set; }
        public Nullable<long> Main_theme { get; set; }
        public string Text { get; set; }
        public Nullable<System.DateTime> Publication_date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Themes_messages> Themes_messages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Themes> Themes1 { get; set; }
        public virtual Themes Themes2 { get; set; }
        public virtual AspNetUsers AspNetUsers { get; set; }
    }
}
